[package]
name = "hello-rust"
version = "0.1.0"
authors = ["Stephen Woods <stephen.woods@salesforce.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.11"
rand  = "0.7.3"

